phase: 'train' # remeber to modify it to test
isTrain: True
dataset_mode: 'celebahq'
no_pairing_check: True
real_reference_probability: 1.0
hard_reference_probability: 0.3
video_like: True
load_size: 256
crop_size: 256
preprocess_mode: 'resize_and_crop'
max_dataset_size: 99999999999
no_flip: True
dataroot: '/data/yashengsun/local_storage/CelebAMask-HQ/'
task_description: 'translate it a realistic image'
inverse_task_description: 'translate it to segmentation mask'
